### ISSUE TITLE
SNES Integration not loading roms

### ISSUE THREAD

**Issue by juliettangom** [AHCoder/galaxy-integration-snes#3]
The integration was working initially. I had it loading roms and playing them until I restarted the client and it didn't read the roms anymore and the "play" command switched to "install". Now attempting to reinstall the plugin doesn't import the games. 

I believe that since I have several of the other integrations you use, the requests are throttling the Giant Bomb api. Giant Bomb suggests having apps cache responses to prevent throttling. Is that a thing that could be implemented? I don't want my API key to get rate limited every time I turn on GOG.

**Comment by BuryTomorrow12** [comment]
Same issue, and seems dev isn't present on this project. Too bad, because I don't know of any other SNES plugin for Galaxy. You can always manually link the emulator but it's not the same.
