### ISSUE TITLE
Plugin crashes during connection

### ISSUE THREAD

**Issue by jamessteinfeldt** [AHCoder/galaxy-integration-snes#4]
Followed the setup instructions and I get "Plug has crashed. Retry." every time I try to Connect the plug-in in settings.  Any advice?

**Comment by Ubivis** [comment]
Same for me...

have ranamed and put the Plugin into the correct folder, updated API-Key, bsnes Folder and Rom Folder (Network-Drive). 

After connection of the plugin, in works for about 20 seconds and then crashes.

**Comment by nduriez** [comment]
I had the same problem and investigate a bit, from what i got,
the plugin crash with some roms (for me it was _Kyle Petty's No Fear Racing.smc_
the last logged line before the plugin crashed was 
`2020-05-16 12:04:58,295 - galaxy.task_manager - DEBUG - Task manager jsonrpc server: creating task 7 (import_local_games)`

After removing this rom from my rom folder, the plugin stopped crashed.
