### ISSUE TITLE
Unable to launch the same game twice in a row.

### ISSUE THREAD

**Issue by POD-io** [AHCoder/galaxy-integration-snes#5]
After quitting an SNES game from BSNES, the game is unable to be launched again. It seemed like GOG thinks the game is still running, or something is preventing from launching that same game.

I am able to launch another SNES game, and this will then allow me to launch the first game.

**Comment by PRAEst-76** [comment]
I have a similar issue where I click "play" and nothing happens other than the "play" icon goes grey. roms are listed and bsnes loads them fine when run independently. I've doublechecked the path to bsnes is correct (I'm using C:\Program Files (x86)\bsnes) and even tried moving it to other locations.

The nes integration with mesen works fine.

Had a look at the logs in C:\ProgramData\GOG.com\Galaxy\logs and can't seen an obvious issue.

https://pastebin.com/pWjB1wJK
